set parquet.block.size=33554432;
--set dfs.block.size=134217728;
-- set parquet.enable.bloom.filter=true;
-- set parquet.bloom.filter.enabled=true;
-- set parquet.filter.bloom.enabled=true;
set hive.optimize.index.filter=true;
set hive.optimize.ppd=true;
set hive.exec.reducers.bytes.per.reducer=16777216;
set hive.execution.engine=mr;
use bloom_filter_data;
